.TH "display_t" 3 "Mercredi 17 Janvier 2018" "Version 0.1" "simants" \" -*- nroff -*-
.ad l
.nh
.SH NAME
display_t \- 
.SH SYNOPSIS
.br
.PP
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBdisplay_t\fP (const \fBfractal_land\fP &land, const \fBpheronome\fP &phen, const position_t &pos_nest, const position_t &pos_food, const std::vector< \fBant\fP > &ants, gui::window &win)"
.br
.ti -1c
.RI "\fBdisplay_t\fP (const \fBdisplay_t\fP &)=delete"
.br
.ti -1c
.RI "void \fBdisplay\fP (const std::size_t &compteur)"
.br
.in -1c

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour simants à partir du code source\&.
